# Streamlit Secrets Configuration
# 로컬 개발용 - 실제 토큰은 여기에 입력하지 마세요!

[default]
# Notion Integration Token (secret_으로 시작)
NOTION_TOKEN = "your_notion_token_here"

# Bedrock 설정
BEDROCK_MODEL_ID = "anthropic.claude-3-5-sonnet-20241022-v2:0"
AWS_DEFAULT_REGION = "us-east-1"

# 모델 파라미터
MAX_TOKENS = 4000
TEMPERATURE = 0.1

# 검색 설정
MAX_SEARCH_RESULTS = 5

# 개발 모드 설정
DEBUG_MODE = true
